### ISSUE TITLE
furikake init の追加

### ISSUE THREAD

**Issue by inokappa** [inokappa/furikake#25]
* .furikake.yml の雛形自動生成
* 以下のようなイメージ

```yaml
resources:
  aws:
    - ec2
    - rds
    - clb
backlog:
  projects:
    - space_id: 'your-backlog-space-id'
      api_key: 'your-backlog-api-key'
      top_level_domain: 'your-backlog-top-level-domain'
      wiki_id: your-wiki-id
      wiki_name: 'your-wiki-name'
      header: >
        # Test Header

        [toc]

        ## Sub Header
      footer: >
        ## Test Footer

        ### Sub Footer
```

* `resources` キーにはドキュメント化したいリソースの一覧を出力する
